# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CNUSignal' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CNUSignal
pod 'Firebase'
pod 'Firebase/Auth'
end
